version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.9.4
      - image: redis:3.0.7-alpine
    working_directory: /go/src/github.com/ngs/ts-dakoku
    steps:
      - checkout
      - run: make test
      - run: go get github.com/mattn/goveralls
      - run: goveralls -coverprofile=coverage/cover.out -service=circle-ci
      - store_artifacts:
          path: coverage
          destination: coverage

workflows:
  version: 2
  test:
    jobs:
      - test
